03-Oct-25 08:46:12 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-002' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 555, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 112, in drm_handler
    if int(raw_text) > len(links) :
       ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-002'
03-Oct-25 08:46:43 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-002' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 555, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 112, in drm_handler
    if int(raw_text) > len(links) :
       ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-002'
03-Oct-25 08:49:13 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-002' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 562, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 213, in drm_handler
    count =int(raw_text)
       ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-002'
03-Oct-25 09:03:18 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-99' coro=<Client.handle_updates() done, defined at /home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/client.py:627> exception=OperationalError('attempt to write a readonly database')> [base_events.py:1833]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/client.py", line 632, in handle_updates
    await self.fetch_peers(updates.users),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/client.py", line 622, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 159, in update_peers
    self.conn.executemany(
sqlite3.OperationalError: attempt to write a readonly database
03-Oct-25 09:10:23 - ERROR - Unhandled exception: Telegram says: [400 PEER_ID_INVALID]  Pyrogram 2.3.68 thinks: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 63, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 5680454765'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 125, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 5680454765'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 562, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 46, in drm_handler
    await bot.send_document(OWNER, x)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_document.py", line 253, in send_document
    peer=await self.resolve_peer(chat_id),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 127, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID]  Pyrogram 2.3.68 thinks: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
03-Oct-25 09:19:49 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-002' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 562, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 550, in drm_handler
    success_count = len(links) - int(raw_text) - failed_count + 1
                                 ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-002'
10-Oct-25 19:06:51 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-079' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 563, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 551, in drm_handler
    success_count = len(links) - int(raw_text) - failed_count + 1
                                 ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-079'
10-Oct-25 19:12:47 - ERROR - Unhandled exception: invalid literal for int() with base 10: '001-079' [dispatcher.py:433]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 378, in _dispatch_to_handlers
    await self._execute_handler(handler, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 405, in _execute_handler
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/runner/workspace/modules/drm_handler.py", line 563, in call_drm_handler
    await drm_handler(bot, m)
  File "/home/runner/workspace/modules/drm_handler.py", line 551, in drm_handler
    success_count = len(links) - int(raw_text) - failed_count + 1
                                 ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '001-079'
